# ~/.config/alacritty/alacritty.toml

# Terminal Emulator Settings
[window]
padding = { x = 20, y = 20 }
decorations = "full"
opacity = 1

[scrolling]
history = 10000
multiplier = 3

# Font
[font]
size = 13

[font.normal]
family = "Sono"
style = "Medium"

[font.bold]
family = "Sono"
style = "Bold"

[font.italic]
family = "Sono"
style = "Italic"

[font.bold_italic]
family = "Sono"
style = "Bold Italic"

# Cursor
[cursor]
style = "Beam"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

# Colors
[colors.primary]
background = "#0f0f0f"
foreground = "#E8E3E3"

# Normal colors
[colors.normal]
black = "#151515"
red = "#B66467"
green = "#8C977D"
yellow = "#D9BC8C"
blue = "#8DA3B9"
magenta = "#A988B0"
cyan = "#8AA6A2"
white = "#E8E3E3"

# Bright colors
[colors.bright]
black = "#646464"
red = "#B66467"
green = "#8C977D"
yellow = "#D9BC8C"
blue = "#8DA3B9"
magenta = "#A988B0"
cyan = "#8AA6A2"
white = "#E8E3E3"

# Cursor colors
[colors.cursor]
text = "#151515"
cursor = "#E8E3E3"

# Selection colors
[colors.selection]
text = "#151515"
background = "#E8E3E3"

[terminal.shell]
program = "/bin/bash"
args = ["-c", "setxkbmap -layout us,ru -option grp:alt_shift_toggle && exec fish"]
# или для zsh:
# args = ["-c", "setxkbmap us,ru -option grp:alt_shift_toggle && exec zsh"]

# Search colors
[colors.search]
matches = { foreground = "#151515", background = "#8C977D" }
focused_match = { foreground = "#151515", background = "#D9BC8C" }

[terminal]
